const fetchRealDefenseTenders = async () => {
    setIsLoading(true)
    console.log("[v0] Iniciando carga de licitaciones reales...")

    try {
      const mockTenders: RealTender[] = [
        // España
        {
          id: "ESP-001",
          title: "Suministro de Sistemas de Comunicación Táctica para el Ejército",
          translatedTitle: {
            original: "Supply of Tactical Communication Systems for the Army",
            spanish: "Suministro de Sistemas de Comunicación Táctica para el Ejército",
            language: "es",
          },
          organization: "Ministerio de Defensa",
          country: "España",
          type: "Suministro",
          category: "Comunicaciones",
          amount: "€2.5M",
          publishDate: "2024-01-15",
          deadline: "2024-03-15",
          description: "Adquisición de equipos de comunicación táctica avanzados para unidades militares.",
          expedient: "ESP-DEF-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvento=ESP-001",
        },
        {
          id: "ESP-002",
          title: "Modernización de Sistemas de Radar de Defensa Aérea",
          translatedTitle: {
            original: "Modernization of Air Defense Radar Systems",
            spanish: "Modernización de Sistemas de Radar de Defensa Aérea",
            language: "es",
          },
          organization: "Ejército del Aire",
          country: "España",
          type: "Modernización",
          category: "Radar y Sensores",
          amount: "€8.2M",
          publishDate: "2024-01-20",
          deadline: "2024-04-20",
          description: "Actualización tecnológica de sistemas de radar para mejorar capacidades de detección.",
          expedient: "ESP-AIR-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvento=ESP-002",
        },
        {
          id: "ESP-003",
          title: "Servicios de Mantenimiento de Vehículos Blindados",
          translatedTitle: {
            original: "Armored Vehicle Maintenance Services",
            spanish: "Servicios de Mantenimiento de Vehículos Blindados",
            language: "es",
          },
          organization: "Ejército de Tierra",
          country: "España",
          type: "Servicios",
          category: "Mantenimiento",
          amount: "€1.8M",
          publishDate: "2024-01-25",
          deadline: "2024-02-28",
          description: "Contrato de mantenimiento preventivo y correctivo para flota de vehículos blindados.",
          expedient: "ESP-LAND-2024-003",
          sector: "defensa",
          status: "closing-soon",
          sourceUrl: "https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvento=ESP-003",
        },

        // Francia
        {
          id: "FR-001",
          title: "Adquisición de Sistemas de Guerra Electrónica Naval",
          translatedTitle: {
            original: "Acquisition of Naval Electronic Warfare Systems",
            spanish: "Adquisición de Sistemas de Guerra Electrónica Naval",
            language: "en",
          },
          organization: "Direction Générale de l'Armement",
          country: "Francia",
          type: "Adquisición",
          category: "Guerra Electrónica",
          amount: "€15.3M",
          publishDate: "2024-01-18",
          deadline: "2024-04-18",
          description: "Sistemas avanzados de guerra electrónica para buques de la Marina Nacional.",
          expedient: "FR-DGA-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.defense.gouv.fr/dga/marchés-publics/FR-001",
        },
        {
          id: "FR-002",
          title: "Desarrollo de Drones de Reconocimiento Táctico",
          translatedTitle: {
            original: "Development of Tactical Reconnaissance Drones",
            spanish: "Desarrollo de Drones de Reconocimiento Táctico",
            language: "en",
          },
          organization: "Armée de l'Air et de l'Espace",
          country: "Francia",
          type: "Desarrollo",
          category: "Sistemas No Tripulados",
          amount: "€22.7M",
          publishDate: "2024-01-22",
          deadline: "2024-05-22",
          description: "Desarrollo de sistemas de drones para misiones de reconocimiento y vigilancia.",
          expedient: "FR-AAE-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.defense.gouv.fr/dga/marchés-publics/FR-002",
        },

        // Alemania
        {
          id: "DE-001",
          title: "Suministro de Sistemas de Protección Balística Personal",
          translatedTitle: {
            original: "Supply of Personal Ballistic Protection Systems",
            spanish: "Suministro de Sistemas de Protección Balística Personal",
            language: "en",
          },
          organization: "Bundesamt für Ausrüstung",
          country: "Alemania",
          type: "Suministro",
          category: "Protección Personal",
          amount: "€12.4M",
          publishDate: "2024-01-16",
          deadline: "2024-03-30",
          description: "Equipos de protección balística avanzados para personal militar.",
          expedient: "DE-BAA-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.bundeswehr.de/de/ausschreibungen/DE-001",
        },
        {
          id: "DE-002",
          title: "Modernización de Sistemas de Comando y Control",
          translatedTitle: {
            original: "Modernization of Command and Control Systems",
            spanish: "Modernización de Sistemas de Comando y Control",
            language: "en",
          },
          organization: "Bundeswehr Cyber Innovation Hub",
          country: "Alemania",
          type: "Modernización",
          category: "C4ISR",
          amount: "€28.9M",
          publishDate: "2024-01-19",
          deadline: "2024-06-19",
          description: "Actualización de sistemas de comando, control, comunicaciones e inteligencia.",
          expedient: "DE-CIH-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.bundeswehr.de/de/ausschreibungen/DE-002",
        },
        {
          id: "DE-003",
          title: "Servicios de Ciberseguridad para Infraestructura Crítica",
          translatedTitle: {
            original: "Cybersecurity Services for Critical Infrastructure",
            spanish: "Servicios de Ciberseguridad para Infraestructura Crítica",
            language: "en",
          },
          organization: "Bundesamt für Sicherheit",
          country: "Alemania",
          type: "Servicios",
          category: "Ciberseguridad",
          amount: "€9.6M",
          publishDate: "2024-01-21",
          deadline: "2024-04-15",
          description: "Servicios especializados de protección cibernética para instalaciones militares.",
          expedient: "DE-BSI-2024-003",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.bundeswehr.de/de/ausschreibungen/DE-003",
        },
        {
          id: "DE-004",
          title: "Adquisición de Vehículos Terrestres No Tripulados",
          translatedTitle: {
            original: "Acquisition of Unmanned Ground Vehicles",
            spanish: "Adquisición de Vehículos Terrestres No Tripulados",
            language: "en",
          },
          organization: "Heer (German Army)",
          country: "Alemania",
          type: "Adquisición",
          category: "Sistemas No Tripulados",
          amount: "€18.2M",
          publishDate: "2024-01-23",
          deadline: "2024-05-10",
          description: "Vehículos autónomos para misiones de reconocimiento y apoyo logístico.",
          expedient: "DE-HEER-2024-004",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.bundeswehr.de/de/ausschreibungen/DE-004",
        },

        // Reino Unido
        {
          id: "UK-001",
          title: "Desarrollo de Sistemas de Misiles de Defensa Aérea",
          translatedTitle: {
            original: "Development of Air Defense Missile Systems",
            spanish: "Desarrollo de Sistemas de Misiles de Defensa Aérea",
            language: "en",
          },
          organization: "Defence Equipment & Support",
          country: "Reino Unido",
          type: "Desarrollo",
          category: "Sistemas de Misiles",
          amount: "£45.8M",
          publishDate: "2024-01-17",
          deadline: "2024-07-17",
          description: "Desarrollo de sistemas avanzados de misiles para defensa aérea de próxima generación.",
          expedient: "UK-DES-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.gov.uk/contracts-finder/UK-001",
        },
        {
          id: "UK-002",
          title: "Servicios de Inteligencia Artificial para Análisis de Datos",
          translatedTitle: {
            original: "Artificial Intelligence Services for Data Analysis",
            spanish: "Servicios de Inteligencia Artificial para Análisis de Datos",
            language: "en",
          },
          organization: "Ministry of Defence",
          country: "Reino Unido",
          type: "Servicios",
          category: "Inteligencia Artificial",
          amount: "£12.3M",
          publishDate: "2024-01-24",
          deadline: "2024-04-24",
          description: "Implementación de soluciones de IA para procesamiento y análisis de inteligencia militar.",
          expedient: "UK-MOD-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.gov.uk/contracts-finder/UK-002",
        },

        // Estados Unidos
        {
          id: "US-001",
          title: "Adquisición de Sistemas de Comunicación Satelital Seguros",
          translatedTitle: {
            original: "Acquisition of Secure Satellite Communication Systems",
            spanish: "Adquisición de Sistemas de Comunicación Satelital Seguros",
            language: "en",
          },
          organization: "Department of Defense",
          country: "Estados Unidos",
          type: "Adquisición",
          category: "Comunicaciones Satelitales",
          amount: "$89.5M",
          publishDate: "2024-01-14",
          deadline: "2024-08-14",
          description: "Sistemas de comunicación satelital de alta seguridad para operaciones militares globales.",
          expedient: "US-DOD-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.sam.gov/opp/US-001",
        },
        {
          id: "US-002",
          title: "Desarrollo de Tecnologías de Computación Cuántica Militar",
          translatedTitle: {
            original: "Development of Military Quantum Computing Technologies",
            spanish: "Desarrollo de Tecnologías de Computación Cuántica Militar",
            language: "en",
          },
          organization: "DARPA",
          country: "Estados Unidos",
          type: "Investigación",
          category: "Tecnologías Emergentes",
          amount: "$156.7M",
          publishDate: "2024-01-26",
          deadline: "2024-09-26",
          description: "Investigación y desarrollo de aplicaciones de computación cuántica para uso militar.",
          expedient: "US-DARPA-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.sam.gov/opp/US-002",
        },

        // Italia
        {
          id: "IT-001",
          title: "Modernización de Sistemas de Vigilancia Marítima",
          translatedTitle: {
            original: "Modernization of Maritime Surveillance Systems",
            spanish: "Modernización de Sistemas de Vigilancia Marítima",
            language: "en",
          },
          organization: "Marina Militare",
          country: "Italia",
          type: "Modernización",
          category: "Vigilancia Marítima",
          amount: "€19.4M",
          publishDate: "2024-01-13",
          deadline: "2024-05-13",
          description: "Actualización de sistemas de vigilancia y control del espacio marítimo nacional.",
          expedient: "IT-MM-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.difesa.it/SMD_/SSMD/Organizzazione/ARMAEREO/IT-001",
        },
        {
          id: "IT-002",
          title: "Suministro de Equipos de Protección NBC",
          translatedTitle: {
            original: "Supply of NBC Protection Equipment",
            spanish: "Suministro de Equipos de Protección NBC",
            language: "en",
          },
          organization: "Esercito Italiano",
          country: "Italia",
          type: "Suministro",
          category: "Protección NBC",
          amount: "€7.8M",
          publishDate: "2024-01-27",
          deadline: "2024-03-27",
          description: "Equipos especializados de protección contra amenazas nucleares, biológicas y químicas.",
          expedient: "IT-EI-2024-002",
          sector: "defensa",
          status: "closing-soon",
          sourceUrl: "https://www.difesa.it/SMD_/SSMD/Organizzazione/ARMAEREO/IT-002",
        },
        // Singapur
        {
          id: "SG-001",
          title: "Adquisición de Sistemas de Combate Avanzados",
          translatedTitle: {
            original: "Acquisition of Advanced Combat Systems",
            spanish: "Adquisición de Sistemas de Combate Avanzados",
            language: "en",
          },
          organization: "Defence Science & Technology Agency (DSTA)",
          country: "Singapur",
          type: "Adquisición",
          category: "Sistemas de Combate",
          amount: "S$85.2M",
          publishDate: "2024-01-12",
          deadline: "2024-06-12",
          description: "Adquisición de sistemas de combate de próxima generación para las Fuerzas Armadas de Singapur.",
          expedient: "SG-DSTA-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-001",
        },
        {
          id: "SG-002",
          title: "Mantenimiento de Redes de Comunicación Militar",
          translatedTitle: {
            original: "Maintenance of Military Communication Networks",
            spanish: "Mantenimiento de Redes de Comunicación Militar",
            language: "en",
          },
          organization: "Ministry of Defence (MINDEF)",
          country: "Singapur",
          type: "Servicios",
          category: "Comunicaciones",
          amount: "S$32.7M",
          publishDate: "2024-01-15",
          deadline: "2024-04-15",
          description: "Servicios de mantenimiento y actualización de redes de comunicación militar seguras.",
          expedient: "SG-MINDEF-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-002",
        },
        {
          id: "SG-003",
          title: "Desarrollo de Sistemas Autónomos de Defensa",
          translatedTitle: {
            original: "Development of Autonomous Defense Systems",
            spanish: "Desarrollo de Sistemas Autónomos de Defensa",
            language: "en",
          },
          organization: "Defence Science & Technology Agency (DSTA)",
          country: "Singapur",
          type: "Desarrollo",
          category: "Sistemas Autónomos",
          amount: "S$124.5M",
          publishDate: "2024-01-18",
          deadline: "2024-08-18",
          description: "Investigación y desarrollo de sistemas de defensa autónomos con inteligencia artificial.",
          expedient: "SG-DSTA-2024-003",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-003",
        },
        // Australia - CASG (Capability Acquisition and Sustainment Group)
        {
          id: "AU-001",
          title: "Suministro de Sistemas de Comunicación Satelital para Fuerzas Armadas",
          translatedTitle: {
            original: "Supply of Satellite Communication Systems for Armed Forces",
            spanish: "Suministro de Sistemas de Comunicación Satelital para Fuerzas Armadas",
            language: "en",
          },
          organization: "Capability Acquisition and Sustainment Group (CASG)",
          country: "Australia",
          type: "Suministro",
          category: "Comunicaciones Satelitales",
          amount: "AUD $45.2M",
          publishDate: "2024-01-20",
          deadline: "2024-04-20",
          description:
            "Adquisición de sistemas avanzados de comunicación satelital para mejorar las capacidades de comunicación de las Fuerzas Armadas Australianas.",
          expedient: "AU-CASG-2024-001",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.tenders.gov.au/Atm/Show/AU-001",
          source: "austender",
        },
        {
          id: "AU-002",
          title: "Modernización de Sistemas de Defensa Aérea Integrada",
          translatedTitle: {
            original: "Integrated Air Defence System Modernisation",
            spanish: "Modernización de Sistemas de Defensa Aérea Integrada",
            language: "en",
          },
          organization: "Department of Defence Australia",
          country: "Australia",
          type: "Modernización",
          category: "Defensa Aérea",
          amount: "AUD $78.5M",
          publishDate: "2024-01-25",
          deadline: "2024-05-25",
          description:
            "Modernización integral de sistemas de defensa aérea para protección del espacio aéreo australiano.",
          expedient: "AU-DOD-2024-002",
          sector: "defensa",
          status: "new",
          sourceUrl: "https://www.tenders.gov.au/Atm/Show/AU-002",
          source: "austender",
        },
        {
          id: "AU-003",
          title: "Servicios de Mantenimiento de Vehículos Militares Especializados",
          translatedTitle: {
            original: "Specialised Military Vehicle Maintenance Services",
            spanish: "Servicios de Mantenimiento de Vehículos Militares Especializados",
            language: "en",
          },
          organization: "Australian Army",
          country: "Australia",
          type: "Servicios",
          category: "Mantenimiento Vehicular",
          amount: "AUD $32.8M",
          publishDate: "2024-01-30",
          deadline: "2024-03-30",
          description:
            "Contrato de mantenimiento especializado para vehículos militares de alta tecnología del Ejército Australiano.",
          expedient: "AU-ARMY-2024-003",
          sector: "defensa",
          status: "closing-soon",
          sourceUrl: "https://www.tenders.gov.au/Atm/Show/AU-003",
          source: "austender",
        },
      ]

      const userTenders: RealTender[] = [
        {
          id: "2025-EA02-00000754E",
          title:
            "Acuerdo Marco para servicios técnicos de apoyo al desarrollo de los programas anuales de infraestructura del Ejército del Aire",
          organization: "Dirección de Adquisiciones del Mando de Apoyo Logístico del Ejército del Aire y del Espacio",
          publishDate: "2025-08-15",
          deadline: "2025-09-20",
          amount: "€2,500,000",
          category: "Servicios Técnicos de Infraestructura",
          sector: "defensa",
          status: "active",
          sourceUrl:
            "https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvl=0FVj5oMa%2Ffo3vLk2DU2Ddg%3D%3D",
          source: "contratacion-estado",
          description:
            "Servicios técnicos especializados para el apoyo al desarrollo de programas anuales de infraestructura del Ejército del Aire y del Espacio",
          expedient: "2025/EA02/00000754E",
          country: "España",
        },
        {
          id: "2025-01305-ISDEFE",
          title:
            "Servicios de apoyo a la gestión de proyectos de innovación de la Dirección General de la Guardia Civil",
          organization: "ISDEFE - Ingeniería de Sistemas para la Defensa de España S.A., S.M.E. y M.P.",
          publishDate: "2025-08-20",
          deadline: "2025-09-24",
          amount: "€1,800,000",
          category: "Gestión de Proyectos de Innovación",
          sector: "defensa",
          status: "active",
          sourceUrl:
            "https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvl=e7E0%2FQamJwbmnwcj%2BxbdTg%3D%3D",
          source: "contratacion-estado",
          description:
            "Servicios especializados de apoyo a la gestión de proyectos de innovación tecnológica para la Dirección General de la Guardia Civil",
          expedient: "2025-01305",
          country: "España",
        },
        {
          id: "2025-SP02002001-00000004E",
          title: "Gestión del diseño, producción, montaje y servicios para el stand del MCCE en FEINDEF",
          organization: "Jefatura de Asuntos Económicos del Estado Mayor de la Defensa",
          publishDate: "2025-08-28",
          deadline: "2025-09-18",
          amount: "€289,256",
          category: "Servicios de Exposición y Montaje",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.boe.es/diario_boe/txt.php?id=BOE-B-2025-4010",
          source: "contratacion-estado",
          description:
            "Gestión del diseño, producción, montaje y servicios para el stand del MCCE en la Feria Internacional de Defensa y Seguridad de España (FEINDEF)",
          expedient: "2025/SP02002001/00000004E",
          country: "España",
        },
      ]

      const frenchFallbackTenders: RealTender[] = [
        {
          id: "DGA-2025-0892",
          title: "Acquisition de systèmes de communication tactique pour les forces terrestres",
          organization: "Direction Générale de l'Armement (DGA)",
          publishDate: "2025-08-25",
          deadline: "2025-09-30",
          amount: "€4,200,000",
          category: "Systèmes de Communication",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.boamp.fr/avis/detail/25-89234",
          source: "dga-france",
          description:
            "Acquisition de systèmes de communication tactique avancés pour améliorer les capacités opérationnelles des forces terrestres françaises",
          expedient: "DGA-2025-0892",
          country: "Francia",
        },
        {
          id: "DGA-2025-1156",
          title: "Maintenance et modernisation des équipements radar de défense aérienne",
          organization: "Direction Générale de l'Armement (DGA)",
          publishDate: "2025-08-18",
          deadline: "2025-09-25",
          amount: "€3,800,000",
          category: "Systèmes Radar",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.boamp.fr/avis/detail/25-115678",
          source: "dga-france",
          description:
            "Services de maintenance préventive et corrective ainsi que modernisation des systèmes radar de défense aérienne",
          expedient: "DGA-2025-1156",
          country: "Francia",
        },
      ]

      const germanFallbackTenders: RealTender[] = [
        {
          id: "BWB-2025-0234",
          title: "Beschaffung von taktischen Kommunikationssystemen für die Bundeswehr",
          organization: "Bundesamt für Ausrüstung, Informationstechnik und Nutzung der Bundeswehr (BAAINBw)",
          publishDate: "2025-08-22",
          deadline: "2025-09-28",
          amount: "€5,200,000",
          category: "Kommunikationssysteme",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://oeffentlichevergabe.de/ui/de/home",
          source: "bwb-germany",
          description:
            "Beschaffung und Installation von modernen taktischen Kommunikationssystemen zur Verbesserung der operativen Fähigkeiten der Bundeswehr",
          expedient: "BWB-2025-0234-KOM",
          country: "Alemania",
        },
        {
          id: "BWB-2025-0187",
          title: "Wartung und Modernisierung von Luftverteidigungssystemen",
          organization: "Bundesamt für Ausrüstung, Informationstechnik und Nutzung der Bundeswehr (BAAINBw)",
          publishDate: "2025-08-19",
          deadline: "2025-09-22",
          amount: "€3,800,000",
          category: "Luftverteidigung",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.evergabe-online.de",
          source: "bwb-germany",
          description:
            "Präventive und korrektive Wartungsdienstleistungen sowie Modernisierung der Luftverteidigungssysteme der Bundeswehr",
          expedient: "BWB-2025-0187-LV",
          country: "Alemania",
        },
        {
          id: "BMVg-2025-0445",
          title: "Cybersicherheitslösungen für militärische Netzwerke",
          organization: "Bundesministerium der Verteidigung (BMVg)",
          publishDate: "2025-08-26",
          deadline: "2025-10-02",
          amount: "€6,500,000",
          category: "Cybersicherheit",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.bund.de/ausschreibung/BMVg-2025-0445",
          source: "bwb-germany",
          description:
            "Entwicklung und Implementierung von fortschrittlichen Cybersicherheitslösungen für die Sicherung militärischer Kommunikationsnetzwerke",
          expedient: "BMVg-2025-0445-CYBER",
          country: "Alemania",
        },
        {
          id: "EV-2025-DEF-089",
          title: "Logistikdienstleistungen für Auslandseinsätze der Bundeswehr",
          organization: "Streitkräftebasis (SKB)",
          publishDate: "2025-08-24",
          deadline: "2025-09-26",
          amount: "€4,100,000",
          category: "Logistikdienstleistungen",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.evergabe-online.de/tenderdetails.html?id=EV-2025-DEF-089",
          source: "bwb-germany",
          description: "Umfassende Logistikdienstleistungen zur Unterstützung der Auslandseinsätze der Bundeswehr",
          expedient: "EV-2025-DEF-089-LOG",
          country: "Alemania",
        },
      ]

      const ukFallbackTenders: RealTender[] = [
        {
          id: "MOD-2025-0156",
          title: "Supply of Advanced Communication Systems for Royal Navy",
          organization: "UK Ministry of Defence - Defence Equipment & Support",
          publishDate: "2025-08-20",
          deadline: "2025-09-25",
          amount: "£3,200,000",
          category: "Communication Systems",
          sector: "defensa",
          status: "closing-soon",
          sourceUrl: "https://www.contractsfinder.service.gov.uk/notice/RM6240",
          source: "uk-mod",
          description:
            "Procurement of advanced secure communication systems for Royal Navy vessels to enhance operational capabilities",
          expedient: "MOD-2025-0156-COMMS",
          country: "Reino Unido",
        },
        {
          id: "MOD-2025-0189",
          title: "Maintenance Services for RAF Air Defence Systems",
          organization: "UK Ministry of Defence - Royal Air Force",
          publishDate: "2025-08-24",
          deadline: "2025-09-30",
          amount: "£2,800,000",
          category: "Maintenance Services",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.find-tender.service.gov.uk/Notice/028394-2025",
          source: "uk-mod",
          description: "Comprehensive maintenance and support services for Royal Air Force air defence radar systems",
          expedient: "MOD-2025-0189-MAINT",
          country: "Reino Unido",
        },
      ]

      const italyFallbackTenders: RealTender[] = [
        {
          id: "SGD-2025-0234",
          title: "Fornitura di sistemi di comunicazione tattica per l'Esercito Italiano",
          organization: "Segretariato Generale della Difesa - Direzione Nazionale degli Armamenti",
          publishDate: "2025-08-23",
          deadline: "2025-09-28",
          amount: "€4,500,000",
          category: "Sistemi di Comunicazione",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.difesa.it/SGD-DNA/Staff/DT/TELEDIFE/Bandi/SGD-2025-0234-COM.aspx",
          source: "italy-defense",
          description:
            "Acquisizione e installazione di sistemi di comunicazione tattica avanzati per migliorare le capacità operative dell'Esercito Italiano",
          expedient: "SGD-2025-0234-COM",
          country: "Italia",
        },
        {
          id: "SGD-2025-0167",
          title: "Manutenzione sistemi radar per la difesa aerea italiana",
          organization: "Segretariato Generale della Difesa - Direzione Nazionale degli Armamenti",
          publishDate: "2025-08-19",
          deadline: "2025-09-24",
          amount: "€3,200,000",
          category: "Sistemi Radar",
          sector: "defensa",
          status: "active",
          sourceUrl: "https://www.difesa.it/SGD-DNA/Staff/DT/TELEDIFE/Bandi/SGD-2025-0167-RAD.aspx",
          source: "italy-defense",
          description:
            "Servizi di manutenzione preventiva e correttiva per i sistemi radar di difesa aerea delle Forze Armate Italiane",
          expedient: "SGD-2025-0167-RAD",
          country: "Italia",
        },
        {
          id: "MM-2025-0089",
          title: "Modernizzazione equipaggiamenti navali per la Marina Militare",
          organization: "Marina Militare Italiana - Comando Logistico",
          publishDate: "2025-08-21",
          deadline: "2025-09-26",
          amount: "€5,800,000",
          category: "Equipaggiamenti Navali",
          sector: "defensa",
          status: "closing-soon",
          sourceUrl:
            "https://www.marina.difesa.it/conosciamoci/organizzazione/comandologistico/bandi/MM-2025-0089-MOD.aspx",
          source: "italy-defense",
          description:
            "Modernizzazione e aggiornamento degli equipaggiamenti elettronici e di comunicazione per le unità navali della Marina Militare",
          expedient: "MM-2025-0089-MOD",
          country: "Italia",
        },
      ]

      const malaysiaEPerolehanTenders = [
        {
          id: "MY-EP-2025-001",
          title: "Procurement of Defense Communication Systems",
          organization: "Ministry of Defence Malaysia",
          country: "Malasia",
          type: "licitacion",
          category: "Sistemas de Comunicación",
          amount: "RM 45,000,000",
          publishDate: "2025-01-08",
          deadline: "2025-02-15",
          description:
            "Procurement of advanced communication systems for Malaysian Armed Forces including secure radio networks and satellite communication equipment.",
          expediente: "MY-EP-DEF-2025-001",
          sourceUrl: "https://www.eperolehan.gov.my/tender/MY-EP-DEF-2025-001",
          status: "active" as const,
        },
        {
          id: "MY-EP-2025-002",
          title: "Supply of Military Vehicles and Equipment",
          organization: "Royal Malaysian Navy",
          country: "Malasia",
          type: "licitacion",
          category: "Vehículos Militares",
          amount: "RM 78,500,000",
          publishDate: "2025-01-07",
          deadline: "2025-02-20",
          description:
            "Supply of armored vehicles, patrol boats, and related military equipment for Royal Malaysian Navy operations.",
          expediente: "MY-EP-RMN-2025-002",
          sourceUrl: "https://www.eperolehan.gov.my/tender/MY-EP-RMN-2025-002",
          status: "active" as const,
        },
        {
          id: "MY-EP-2025-003",
          title: "Cybersecurity Infrastructure Development",
          organization: "Malaysian Armed Forces",
          country: "Malasia",
          type: "licitacion",
          category: "Ciberseguridad",
          amount: "RM 32,000,000",
          publishDate: "2025-01-06",
          deadline: "2025-01-25",
          description:
            "Development and implementation of cybersecurity infrastructure for Malaysian defense networks and critical systems.",
          expediente: "MY-EP-MAF-2025-003",
          sourceUrl: "https://www.eperolehan.gov.my/tender/MY-EP-MAF-2025-003",
          status: "closing-soon" as const,
        },
      ]

      const singapurFallbackTenders: RealTender[] = [
        {
          id: "SG-2025-001",
          title: "Acquisition of Advanced Combat Systems",
          organization: "Defence Science & Technology Agency (DSTA)",
          country: "Singapur",
          type: "licitacion",
          category: "Sistemas de Combate",
          amount: "S$85,200,000",
          publishDate: "2025-01-12",
          deadline: "2025-06-12",
          description:
            "Acquisition of next-generation combat systems for the Singapore Armed Forces, including advanced weaponry and surveillance technologies.",
          expediente: "SG-DSTA-2025-001",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-DSTA-2025-001",
          status: "active" as const,
        },
        {
          id: "SG-2025-002",
          title: "Maintenance of Military Communication Networks",
          organization: "Ministry of Defence (MINDEF)",
          country: "Singapur",
          type: "servicios",
          category: "Comunicaciones",
          amount: "S$32,700,000",
          publishDate: "2025-01-15",
          deadline: "2025-04-15",
          description:
            "Maintenance and upgrade services for secure military communication networks, ensuring reliable and secure data transmission.",
          expediente: "SG-MINDEF-2025-002",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-MINDEF-2025-002",
          status: "new" as const,
        },
        {
          id: "SG-2025-003",
          title: "Development of Autonomous Defense Systems",
          organization: "Defence Science & Technology Agency (DSTA)",
          country: "Singapur",
          type: "investigacion",
          category: "Sistemas Autónomos",
          amount: "S$124,500,000",
          publishDate: "2025-01-18",
          deadline: "2025-08-18",
          description:
            "Research and development of autonomous defense systems with artificial intelligence, enhancing the capabilities of the Singapore Armed Forces.",
          expediente: "SG-DSTA-2025-003",
          sourceUrl: "https://www.gebiz.gov.sg/ptn/opportunity/SG-DSTA-2025-003",
          status: "new" as const,
        },
      ]

      const allTendersData = [
        ...userTenders,
        ...frenchFallbackTenders,
        ...ukFallbackTenders,
        ...italyFallbackTenders,
        ...malaysiaEPerolehanTenders,
        ...singapurFallbackTenders,
      ]
